import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/component/NavBar";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Adit SteelSeries",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  let isLoggedIn = false
  const authorization = cookies().get(`Authorization`)
  if(authorization?.name) isLoggedIn = true

  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar isLoggedIn={isLoggedIn}/>
        {children}
        </body>
    </html>
  );
}
